on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: registry2xiangsc.azurecr.io
        username: ${{ secrets.acr_registry2xiangsc_username }}
        password: ${{ secrets.acr_registry2xiangsc_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t registry2xiangsc.azurecr.io/k8sxiangsc:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push registry2xiangsc.azurecr.io/k8sxiangsc:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_k8sxiangsc_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep k8s-xiangsc8a9e | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace k8s-xiangsc8a9e`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: k8s-xiangsc8a9e
        container-registry-url: registry2xiangsc.azurecr.io
        container-registry-username: ${{ secrets.acr_registry2xiangsc_username }}
        container-registry-password: ${{ secrets.acr_registry2xiangsc_password }}
        secret-name: k8sxiangscdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: k8s-xiangsc8a9e
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          registry2xiangsc.azurecr.io/k8sxiangsc:${{ github.sha }}
        imagepullsecrets: |
          k8sxiangscdockerauth
